name: Full-Stack CI/CD Pipeline

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Set up Node.js for backend
      - name: Set up Node.js for Backend
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Install backend dependencies
      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      # Set up Node.js for frontend
      - name: Set up Node.js for Frontend
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Install frontend dependencies
      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      # Build frontend for production
      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      # Run tests for backend (you can skip if not needed)
      - name: Run Backend Tests
        run: |
          cd backend
          npm test
